version: 2.1

orbs:
  cypress: cypress-io/cypress@1.26.0

jobs:
  build:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run: yarn cy:info

workflows:
  version: 2
  setting_test:
    jobs:
      - build