version: 2.1

jobs:
  build:
    branches:
      only:
        - setting-circleci
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run: echo "Hello, World!"